name: Build & Deploy to ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: poc-portal

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- APP IMAGE ----------------
      - name: Build & Push App Image
        run: |
          docker build -t app-image ./app
          docker tag app-image:latest ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:app
          docker push ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:app

      # ---------------- JMETER IMAGE ----------------
      - name: Build & Push JMeter Image
        run: |
          docker build -t jmeter-image ./jmeter
          docker tag jmeter-image:latest ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:jmeter
          docker push ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:jmeter

      # ---------------- LOCUST IMAGE ----------------
      - name: Build & Push Locust Image
        run: |
          docker build -t locust-image ./locust
          docker tag locust-image:latest ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:locust
          docker push ${{ steps.login-ecr.outputs.registry }}/testing_load-prod:locust

      # ---------------- DEPLOY ECS ----------------
      - name: Deploy App Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service testing_load \
            --force-new-deployment

      - name: Deploy JMeter Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service jmeter \
            --force-new-deployment

      - name: Deploy Locust Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service locust \
            --force-new-deployment

